### ISSUE TITLE
When the picture above a certain size will crash.

### ISSUE THREAD

**Issue by kilolumen** [sibahota059/TwitterProfilePageBlurr#2]

**Comment by codaman** [comment]
add UIImage+StackBlur.m file 
- (void) applyStackBlurToBuffer:(UInt8_)targetBuffer width:(const int)w height:(const int)h withRadius:(NSUInteger)inradius {
  // Constants
  const int radius = inradius; // Transform unsigned into signed for further operations
  const int wm = w - 1;
  const int hm = h - 1;
  const int wh = w_h;
  const int div = radius + radius + 1;
  const int r1 = radius + 1;
  const int divsum = SQUARE((div+1)>>1);

after this add this line

if (div < 0) {
        return;
    }
